-- Generated from docs/content/mvp-content-bundle-v1.json; draft rows only.
-- The sources array preserves HTTPS URLs and repo:// evidence references as text.
-- Review authenticity and source support require human review; this file is not a publication mechanism.
-- Run only in a separately approved development database after local validation.
begin;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000001'::uuid, 'before-homecoming', 'checklist') on conflict (id) do nothing;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000002'::uuid, 'first-week', 'article') on conflict (id) do nothing;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000003'::uuid, 'daily-log-routines', 'article') on conflict (id) do nothing;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000004'::uuid, 'handling-guide', 'article') on conflict (id) do nothing;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000005'::uuid, 'environment-checklist', 'checklist') on conflict (id) do nothing;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000006'::uuid, 'being-alone-guide', 'article') on conflict (id) do nothing;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000007'::uuid, 'weight-history-guide', 'article') on conflict (id) do nothing;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000008'::uuid, 'health-records-guide', 'article') on conflict (id) do nothing;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000009'::uuid, 'handling-program', 'training_program') on conflict (id) do nothing;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000010'::uuid, 'environment-program', 'training_program') on conflict (id) do nothing;
insert into public.content_items(id, slug, content_type) values ('61000000-0000-4000-8000-000000000011'::uuid, 'being-alone-program', 'training_program') on conflict (id) do nothing;
do $verify_items$
begin
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000001'::uuid and slug='before-homecoming' and content_type='checklist') then raise exception 'content item mismatch: before-homecoming'; end if;
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000002'::uuid and slug='first-week' and content_type='article') then raise exception 'content item mismatch: first-week'; end if;
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000003'::uuid and slug='daily-log-routines' and content_type='article') then raise exception 'content item mismatch: daily-log-routines'; end if;
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000004'::uuid and slug='handling-guide' and content_type='article') then raise exception 'content item mismatch: handling-guide'; end if;
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000005'::uuid and slug='environment-checklist' and content_type='checklist') then raise exception 'content item mismatch: environment-checklist'; end if;
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000006'::uuid and slug='being-alone-guide' and content_type='article') then raise exception 'content item mismatch: being-alone-guide'; end if;
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000007'::uuid and slug='weight-history-guide' and content_type='article') then raise exception 'content item mismatch: weight-history-guide'; end if;
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000008'::uuid and slug='health-records-guide' and content_type='article') then raise exception 'content item mismatch: health-records-guide'; end if;
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000009'::uuid and slug='handling-program' and content_type='training_program') then raise exception 'content item mismatch: handling-program'; end if;
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000010'::uuid and slug='environment-program' and content_type='training_program') then raise exception 'content item mismatch: environment-program'; end if;
  if not exists (select 1 from public.content_items where id='61000000-0000-4000-8000-000000000011'::uuid and slug='being-alone-program' and content_type='training_program') then raise exception 'content item mismatch: being-alone-program'; end if;
end
$verify_items$;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000001'::uuid, '61000000-0000-4000-8000-000000000001'::uuid, 1, 'Förbered hemmet före valpens ankomst', '## En lugn start

- Ordna en lugn viloplats där valpen kan få vara ostörd.
- Gå igenom valpens rum och plocka undan sådant som kan skada valpen eller som du inte vill att den tuggar på.
- Fråga uppfödaren om valpen har en filt eller annan trygg sak hemifrån som kan följa med.

Det här är en förberedelselista före hemkomst. Den är inte en valpålder eller ett träningsschema.', 0, 0, 'draft', ARRAY['https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare']::text[]) on conflict (id) do nothing;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000002'::uuid, '61000000-0000-4000-8000-000000000002'::uuid, 1, 'Första veckan hemma', 'Om valpen nyligen har flyttat hem kan de första dagarna göras lugna och förutsägbara. Ge valpen en trygg viloplats, låt den utforska i egen takt och belöna sådant du gärna vill se mer av. Titta på flera kroppssignaler tillsammans och i sitt sammanhang; en enstaka signal är inte en diagnos. Ge utrymme om valpen verkar obekväm och kontakta veterinär vid oro för hälsan.', 8, 12, 'draft', ARRAY['https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare', 'https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf', 'https://avsab.org/resources/position-statements/', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/behaviour/understanding']::text[]) on conflict (id) do nothing;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000003'::uuid, '61000000-0000-4000-8000-000000000003'::uuid, 1, 'Vardagslogg och rutiner i Tassla', '## Så använder du vardagsloggen

Tryck på en snabbknapp för att lägga till kiss, bajs, mat, sömn, vaken eller promenad. En post får datum och tid och kan ha en kort, frivillig anteckning.

I logghistoriken kan du se poster grupperade efter dag. Du kan ändra eller radera en post och, när det finns äldre poster, hämta fler. Hälsoposter som vikt och veterinärbesök visas under Hälsa i stället.

Loggen hjälper dig att hålla reda på det du själv registrerar. Den tolkar inte hundens behov och upptäcker inte mönster åt dig.', 0, null, 'draft', ARRAY['repo://src/features/puppy-log/README.md', 'repo://src/features/puppy-log/LogScreen.tsx']::text[]) on conflict (id) do nothing;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000004'::uuid, '61000000-0000-4000-8000-000000000004'::uuid, 1, 'Trygg hantering bygger på frivillighet', '## Kort, lugnt och frivilligt

Låt valpen först se och nosa på handen. Belöna lugn nyfikenhet. Om valpen är bekväm kan du prova en mycket kort beröring på en plats den verkar acceptera och sedan pausa.

Låt valpen välja om den vill stanna kvar. Tvinga inte fram beröring eller fasthållning för att genomföra övningen. Målet här är en trygg vardagsvana, inte att utföra en undersökning eller behandling.

Läs flera kroppssignaler tillsammans och i sitt sammanhang; en enstaka signal är inte en diagnos. Att vända bort huvudet, slicka sig om munnen, gäspa, krypa undan eller försöka gå därifrån kan då vara tecken på obehag. Sluta då, ge utrymme och gör nästa försök lättare. Om rädsla eller svår hantering återkommer, be veterinär om hjälp att hitta rätt stöd.', 13, 16, 'draft', ARRAY['https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf', 'https://avsab.org/resources/position-statements/', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/behaviour/understanding']::text[]) on conflict (id) do nothing;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000005'::uuid, '61000000-0000-4000-8000-000000000005'::uuid, 1, 'Trygghet i nya miljöer', '## Innan ni utforskar

- Börja på en lugn plats där valpen kan vila och själv välja att närma sig.
- Plocka undan sådant som kan skada valpen eller som du inte vill att den tuggar på.
- Låt nya vardagsintryck komma gradvis och på ett avstånd där valpen fortfarande verkar bekväm.
- Låt valpen titta, nosa eller gå undan; belöna frivillig nyfikenhet och lugn kontakt.
- Avsluta och skapa mer avstånd om valpen verkar orolig. Försök senare från ett lättare läge.

Socialisering handlar om positiva, gradvisa och individanpassade erfarenheter. Valpen behöver inte hälsa på allt.', 17, 26, 'draft', ARRAY['https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare', 'https://avsab.org/wp-content/uploads/2024/12/Puppy-Socialization-Position-Statement-FINAL.pdf', 'https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf']::text[]) on conflict (id) do nothing;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000006'::uuid, '61000000-0000-4000-8000-000000000006'::uuid, 1, 'Hjälp valpen att vara själv en liten stund', '## Börja med trygghet hemma

Välj en lugn plats där valpen kan vila och ha vatten. Låt platsen vara trevlig även när du är hemma, så att den inte bara förknippas med att du går.

Börja med lite avstånd medan du fortfarande är hemma. Håll övningen så enkel att valpen kan vara lugn och återvänd innan den blir orolig. Gör det gradvis och utifrån just din valps reaktion; det finns ingen minutplan som passar alla.

Om valpen verkar orolig, gör det lättare nästa gång och återgå till det senaste läge där den var lugn. Om oron kvarstår eller är kraftig, kontakta veterinär först. Efter medicinsk bedömning kan veterinären vid behov hänvisa till kvalificerad, belöningsbaserad beteendehjälp. Den här guiden förebygger inte eller behandlar garanterat separationsrelaterade problem.', 27, 52, 'draft', ARRAY['https://www.bluecross.org.uk/advice/dog/behaviour-and-training/preventing-separation-anxiety-in-puppies', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone', 'https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf']::text[]) on conflict (id) do nothing;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000007'::uuid, '61000000-0000-4000-8000-000000000007'::uuid, 1, 'Så fungerar vikthistoriken', '## Lägg till en viktpost

Under Hälsa kan du registrera hundens vikt i kilo och ange datum. Du kan rätta eller radera en post och se dina registrerade vikter i datumordning.

Uppgifterna är ägarregistrerade. Tassla kontrollerar inte om vikten är lämplig, tolkar inte förändringar och ersätter inte en veterinärjournal. Vid frågor om hundens vikt eller tillväxt kan du kontakta veterinär.', 0, null, 'draft', ARRAY['repo://src/features/health/README.md', 'repo://src/features/health/HealthScreen.tsx', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare']::text[]) on conflict (id) do nothing;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000008'::uuid, '61000000-0000-4000-8000-000000000008'::uuid, 1, 'Registrera en utförd vaccination eller ett veterinärbesök', '## Din egen historik

I Hälsa kan du lägga till en post för en vaccination som redan har utförts eller ett veterinärbesök som redan har ägt rum. Ange datum och lägg vid behov till en kort anteckning. Du kan senare ändra eller radera posten.

Uppgifterna är registrerade av dig. De är inte en verifierad journal, ett officiellt vaccinationskort eller ett råd om när nästa vårdbesök ska ske. Fråga veterinär om vaccinationer, symtom eller vård.', 0, null, 'draft', ARRAY['repo://src/features/health/README.md', 'repo://src/features/health/HealthHistoryScreen.tsx', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare']::text[]) on conflict (id) do nothing;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000009'::uuid, '61000000-0000-4000-8000-000000000009'::uuid, 1, 'Trygg hantering i små steg', 'Öva bara när hunden verkar lugn. Belöna frivilligt deltagande och låt hunden gå undan. Stegen är förslag, inte en kalender. Tolka kroppssignaler i sitt sammanhang och tillsammans; en enstaka signal är inte en diagnos. Om hunden visar obehag: avbryt, ge utrymme och återgå nästa gång till ett enklare steg. Vid ihållande oro eller svår hantering, be veterinär om vägledning.', 8, null, 'draft', ARRAY['https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf', 'https://avsab.org/resources/position-statements/', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/behaviour/understanding']::text[]) on conflict (id) do nothing;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000010'::uuid, '61000000-0000-4000-8000-000000000010'::uuid, 1, 'Utforska miljön med trygghet', 'Erbjud vardagens miljöer och ljud i en takt där hunden kan känna sig trygg. Låt den observera, närma sig eller gå undan. Belöna lugn, frivillig utforskning; tvinga inte fram kontakt. Om hunden verkar rädd eller överväldigad, stoppa exponeringen, skapa avstånd och gör nästa försök enklare. Tolka kroppssignaler i sitt sammanhang och tillsammans; en enstaka signal är inte en diagnos. Programmet ersätter inte individuell rådgivning.', 8, null, 'draft', ARRAY['https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare', 'https://avsab.org/wp-content/uploads/2024/12/Puppy-Socialization-Position-Statement-FINAL.pdf', 'https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/behaviour/understanding']::text[]) on conflict (id) do nothing;
insert into public.content_versions(id, content_id, version, title, body, min_age_weeks, max_age_weeks, status, sources) values ('62000000-0000-4000-8000-000000000011'::uuid, '61000000-0000-4000-8000-000000000011'::uuid, 1, 'Öva på att vara själv i hundens takt', 'Gör den valda viloplatsen trygg även när du är hemma. Börja med lite avstånd och håll varje övning så enkel att hunden verkar lugn. Gå vidare först när just din hund är bekväm; programmet har inga fasta minuter eller kalendersteg. Om hunden blir orolig: avbryt, gå tillbaka till senaste läget där den var lugn och kontakta veterinär först vid kvarstående eller kraftig oro. Efter medicinsk bedömning kan veterinären vid behov hänvisa till kvalificerad, belöningsbaserad beteendehjälp.', 8, null, 'draft', ARRAY['https://www.bluecross.org.uk/advice/dog/behaviour-and-training/preventing-separation-anxiety-in-puppies', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone', 'https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf']::text[]) on conflict (id) do nothing;
do $verify_versions$
begin
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000001'::uuid and content_id='61000000-0000-4000-8000-000000000001'::uuid and version=1 and title='Förbered hemmet före valpens ankomst' and body='## En lugn start

- Ordna en lugn viloplats där valpen kan få vara ostörd.
- Gå igenom valpens rum och plocka undan sådant som kan skada valpen eller som du inte vill att den tuggar på.
- Fråga uppfödaren om valpen har en filt eller annan trygg sak hemifrån som kan följa med.

Det här är en förberedelselista före hemkomst. Den är inte en valpålder eller ett träningsschema.' and min_age_weeks=0 and max_age_weeks is not distinct from 0 and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare']::text[]) then raise exception 'content version mismatch: before-homecoming v1'; end if;
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000002'::uuid and content_id='61000000-0000-4000-8000-000000000002'::uuid and version=1 and title='Första veckan hemma' and body='Om valpen nyligen har flyttat hem kan de första dagarna göras lugna och förutsägbara. Ge valpen en trygg viloplats, låt den utforska i egen takt och belöna sådant du gärna vill se mer av. Titta på flera kroppssignaler tillsammans och i sitt sammanhang; en enstaka signal är inte en diagnos. Ge utrymme om valpen verkar obekväm och kontakta veterinär vid oro för hälsan.' and min_age_weeks=8 and max_age_weeks is not distinct from 12 and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare', 'https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf', 'https://avsab.org/resources/position-statements/', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/behaviour/understanding']::text[]) then raise exception 'content version mismatch: first-week v1'; end if;
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000003'::uuid and content_id='61000000-0000-4000-8000-000000000003'::uuid and version=1 and title='Vardagslogg och rutiner i Tassla' and body='## Så använder du vardagsloggen

Tryck på en snabbknapp för att lägga till kiss, bajs, mat, sömn, vaken eller promenad. En post får datum och tid och kan ha en kort, frivillig anteckning.

I logghistoriken kan du se poster grupperade efter dag. Du kan ändra eller radera en post och, när det finns äldre poster, hämta fler. Hälsoposter som vikt och veterinärbesök visas under Hälsa i stället.

Loggen hjälper dig att hålla reda på det du själv registrerar. Den tolkar inte hundens behov och upptäcker inte mönster åt dig.' and min_age_weeks=0 and max_age_weeks is not distinct from null and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['repo://src/features/puppy-log/README.md', 'repo://src/features/puppy-log/LogScreen.tsx']::text[]) then raise exception 'content version mismatch: daily-log-routines v1'; end if;
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000004'::uuid and content_id='61000000-0000-4000-8000-000000000004'::uuid and version=1 and title='Trygg hantering bygger på frivillighet' and body='## Kort, lugnt och frivilligt

Låt valpen först se och nosa på handen. Belöna lugn nyfikenhet. Om valpen är bekväm kan du prova en mycket kort beröring på en plats den verkar acceptera och sedan pausa.

Låt valpen välja om den vill stanna kvar. Tvinga inte fram beröring eller fasthållning för att genomföra övningen. Målet här är en trygg vardagsvana, inte att utföra en undersökning eller behandling.

Läs flera kroppssignaler tillsammans och i sitt sammanhang; en enstaka signal är inte en diagnos. Att vända bort huvudet, slicka sig om munnen, gäspa, krypa undan eller försöka gå därifrån kan då vara tecken på obehag. Sluta då, ge utrymme och gör nästa försök lättare. Om rädsla eller svår hantering återkommer, be veterinär om hjälp att hitta rätt stöd.' and min_age_weeks=13 and max_age_weeks is not distinct from 16 and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf', 'https://avsab.org/resources/position-statements/', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/behaviour/understanding']::text[]) then raise exception 'content version mismatch: handling-guide v1'; end if;
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000005'::uuid and content_id='61000000-0000-4000-8000-000000000005'::uuid and version=1 and title='Trygghet i nya miljöer' and body='## Innan ni utforskar

- Börja på en lugn plats där valpen kan vila och själv välja att närma sig.
- Plocka undan sådant som kan skada valpen eller som du inte vill att den tuggar på.
- Låt nya vardagsintryck komma gradvis och på ett avstånd där valpen fortfarande verkar bekväm.
- Låt valpen titta, nosa eller gå undan; belöna frivillig nyfikenhet och lugn kontakt.
- Avsluta och skapa mer avstånd om valpen verkar orolig. Försök senare från ett lättare läge.

Socialisering handlar om positiva, gradvisa och individanpassade erfarenheter. Valpen behöver inte hälsa på allt.' and min_age_weeks=17 and max_age_weeks is not distinct from 26 and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare', 'https://avsab.org/wp-content/uploads/2024/12/Puppy-Socialization-Position-Statement-FINAL.pdf', 'https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf']::text[]) then raise exception 'content version mismatch: environment-checklist v1'; end if;
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000006'::uuid and content_id='61000000-0000-4000-8000-000000000006'::uuid and version=1 and title='Hjälp valpen att vara själv en liten stund' and body='## Börja med trygghet hemma

Välj en lugn plats där valpen kan vila och ha vatten. Låt platsen vara trevlig även när du är hemma, så att den inte bara förknippas med att du går.

Börja med lite avstånd medan du fortfarande är hemma. Håll övningen så enkel att valpen kan vara lugn och återvänd innan den blir orolig. Gör det gradvis och utifrån just din valps reaktion; det finns ingen minutplan som passar alla.

Om valpen verkar orolig, gör det lättare nästa gång och återgå till det senaste läge där den var lugn. Om oron kvarstår eller är kraftig, kontakta veterinär först. Efter medicinsk bedömning kan veterinären vid behov hänvisa till kvalificerad, belöningsbaserad beteendehjälp. Den här guiden förebygger inte eller behandlar garanterat separationsrelaterade problem.' and min_age_weeks=27 and max_age_weeks is not distinct from 52 and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['https://www.bluecross.org.uk/advice/dog/behaviour-and-training/preventing-separation-anxiety-in-puppies', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone', 'https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf']::text[]) then raise exception 'content version mismatch: being-alone-guide v1'; end if;
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000007'::uuid and content_id='61000000-0000-4000-8000-000000000007'::uuid and version=1 and title='Så fungerar vikthistoriken' and body='## Lägg till en viktpost

Under Hälsa kan du registrera hundens vikt i kilo och ange datum. Du kan rätta eller radera en post och se dina registrerade vikter i datumordning.

Uppgifterna är ägarregistrerade. Tassla kontrollerar inte om vikten är lämplig, tolkar inte förändringar och ersätter inte en veterinärjournal. Vid frågor om hundens vikt eller tillväxt kan du kontakta veterinär.' and min_age_weeks=0 and max_age_weeks is not distinct from null and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['repo://src/features/health/README.md', 'repo://src/features/health/HealthScreen.tsx', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare']::text[]) then raise exception 'content version mismatch: weight-history-guide v1'; end if;
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000008'::uuid and content_id='61000000-0000-4000-8000-000000000008'::uuid and version=1 and title='Registrera en utförd vaccination eller ett veterinärbesök' and body='## Din egen historik

I Hälsa kan du lägga till en post för en vaccination som redan har utförts eller ett veterinärbesök som redan har ägt rum. Ange datum och lägg vid behov till en kort anteckning. Du kan senare ändra eller radera posten.

Uppgifterna är registrerade av dig. De är inte en verifierad journal, ett officiellt vaccinationskort eller ett råd om när nästa vårdbesök ska ske. Fråga veterinär om vaccinationer, symtom eller vård.' and min_age_weeks=0 and max_age_weeks is not distinct from null and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['repo://src/features/health/README.md', 'repo://src/features/health/HealthHistoryScreen.tsx', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare']::text[]) then raise exception 'content version mismatch: health-records-guide v1'; end if;
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000009'::uuid and content_id='61000000-0000-4000-8000-000000000009'::uuid and version=1 and title='Trygg hantering i små steg' and body='Öva bara när hunden verkar lugn. Belöna frivilligt deltagande och låt hunden gå undan. Stegen är förslag, inte en kalender. Tolka kroppssignaler i sitt sammanhang och tillsammans; en enstaka signal är inte en diagnos. Om hunden visar obehag: avbryt, ge utrymme och återgå nästa gång till ett enklare steg. Vid ihållande oro eller svår hantering, be veterinär om vägledning.' and min_age_weeks=8 and max_age_weeks is not distinct from null and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf', 'https://avsab.org/resources/position-statements/', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/behaviour/understanding']::text[]) then raise exception 'content version mismatch: handling-program v1'; end if;
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000010'::uuid and content_id='61000000-0000-4000-8000-000000000010'::uuid and version=1 and title='Utforska miljön med trygghet' and body='Erbjud vardagens miljöer och ljud i en takt där hunden kan känna sig trygg. Låt den observera, närma sig eller gå undan. Belöna lugn, frivillig utforskning; tvinga inte fram kontakt. Om hunden verkar rädd eller överväldigad, stoppa exponeringen, skapa avstånd och gör nästa försök enklare. Tolka kroppssignaler i sitt sammanhang och tillsammans; en enstaka signal är inte en diagnos. Programmet ersätter inte individuell rådgivning.' and min_age_weeks=8 and max_age_weeks is not distinct from null and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['https://www.rspca.org.uk/adviceandwelfare/pets/dogs/health/puppycare', 'https://avsab.org/wp-content/uploads/2024/12/Puppy-Socialization-Position-Statement-FINAL.pdf', 'https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/behaviour/understanding']::text[]) then raise exception 'content version mismatch: environment-program v1'; end if;
  if not exists (select 1 from public.content_versions where id='62000000-0000-4000-8000-000000000011'::uuid and content_id='61000000-0000-4000-8000-000000000011'::uuid and version=1 and title='Öva på att vara själv i hundens takt' and body='Gör den valda viloplatsen trygg även när du är hemma. Börja med lite avstånd och håll varje övning så enkel att hunden verkar lugn. Gå vidare först när just din hund är bekväm; programmet har inga fasta minuter eller kalendersteg. Om hunden blir orolig: avbryt, gå tillbaka till senaste läget där den var lugn och kontakta veterinär först vid kvarstående eller kraftig oro. Efter medicinsk bedömning kan veterinären vid behov hänvisa till kvalificerad, belöningsbaserad beteendehjälp.' and min_age_weeks=8 and max_age_weeks is not distinct from null and status='draft' and reviewed_at is null and review_reference is null and published_at is null and sources=ARRAY['https://www.bluecross.org.uk/advice/dog/behaviour-and-training/preventing-separation-anxiety-in-puppies', 'https://www.rspca.org.uk/adviceandwelfare/pets/dogs/training/leftalone', 'https://avsab.org/wp-content/uploads/2021/08/AVSAB-Humane-Dog-Training-Position-Statement-2021.pdf']::text[]) then raise exception 'content version mismatch: being-alone-program v1'; end if;
end
$verify_versions$;
do $verify_targets$
begin
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000001'::uuid) <> 0 then raise exception 'breed target count mismatch: before-homecoming'; end if;
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000002'::uuid) <> 0 then raise exception 'breed target count mismatch: first-week'; end if;
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000003'::uuid) <> 0 then raise exception 'breed target count mismatch: daily-log-routines'; end if;
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000004'::uuid) <> 0 then raise exception 'breed target count mismatch: handling-guide'; end if;
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000005'::uuid) <> 0 then raise exception 'breed target count mismatch: environment-checklist'; end if;
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000006'::uuid) <> 0 then raise exception 'breed target count mismatch: being-alone-guide'; end if;
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000007'::uuid) <> 0 then raise exception 'breed target count mismatch: weight-history-guide'; end if;
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000008'::uuid) <> 0 then raise exception 'breed target count mismatch: health-records-guide'; end if;
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000009'::uuid) <> 0 then raise exception 'breed target count mismatch: handling-program'; end if;
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000010'::uuid) <> 0 then raise exception 'breed target count mismatch: environment-program'; end if;
  if (select count(*) from public.content_breed_targets where content_version_id='62000000-0000-4000-8000-000000000011'::uuid) <> 0 then raise exception 'breed target count mismatch: being-alone-program'; end if;
end
$verify_targets$;
insert into public.training_steps(id, program_version_id, step_key, position, title, instruction) values ('63000000-0000-4000-8000-000000000001'::uuid, '62000000-0000-4000-8000-000000000009'::uuid, 'voluntary-approach', 1, 'Låt hunden välja kontakt', 'Sitt stilla och erbjud en avslappnad hand en bit ifrån hunden. Belöna om hunden själv närmar sig eller nosar. Försök inte locka den närmare om den väljer att gå undan.') on conflict (id) do nothing;
insert into public.training_steps(id, program_version_id, step_key, position, title, instruction) values ('63000000-0000-4000-8000-000000000002'::uuid, '62000000-0000-4000-8000-000000000009'::uuid, 'brief-touch', 2, 'Prova en kort beröring', 'När hunden självmant söker kontakt och verkar bekväm, prova en lätt, kort beröring på en plats den accepterar. Belöna och pausa direkt. Om den blir stel, vänder bort sig eller går undan (tolka signalerna tillsammans och i sitt sammanhang), sluta och återgå senare till steg 1.') on conflict (id) do nothing;
insert into public.training_steps(id, program_version_id, step_key, position, title, instruction) values ('63000000-0000-4000-8000-000000000003'::uuid, '62000000-0000-4000-8000-000000000009'::uuid, 'choose-repeat', 3, 'Låt hunden välja om ni fortsätter', 'Erbjud samma enkla beröring igen en annan gång och pausa mellan försöken. Fortsätt bara när hunden själv stannar kvar och verkar bekväm. Avsluta om den visar obehag; gör inte övningen till fasthållning.') on conflict (id) do nothing;
insert into public.training_steps(id, program_version_id, step_key, position, title, instruction) values ('63000000-0000-4000-8000-000000000004'::uuid, '62000000-0000-4000-8000-000000000010'::uuid, 'quiet-observe', 1, 'Börja med att titta', 'Välj en lugn och bekant plats. Låt hunden observera en vardagssak på avstånd där den verkar bekväm. Belöna frivillig uppmärksamhet och låt den vila eller gå undan.') on conflict (id) do nothing;
insert into public.training_steps(id, program_version_id, step_key, position, title, instruction) values ('63000000-0000-4000-8000-000000000005'::uuid, '62000000-0000-4000-8000-000000000010'::uuid, 'voluntary-explore', 2, 'Låt hunden närma sig själv', 'När hunden är lugn kan den själv få nosa eller närma sig samma sak. Belöna lugn nyfikenhet. Om den tvekar, stanna på lättare avstånd i stället för att föra den fram.') on conflict (id) do nothing;
insert into public.training_steps(id, program_version_id, step_key, position, title, instruction) values ('63000000-0000-4000-8000-000000000006'::uuid, '62000000-0000-4000-8000-000000000010'::uuid, 'pause-or-backoff', 3, 'Pausa när hunden behöver det', 'Om hunden sänker kroppen, vänder bort sig, slickar sig om munnen eller försöker gå undan, avsluta och öka avståndet. Tolka signalerna tillsammans och i sitt sammanhang; en enstaka signal är inte en diagnos. Prova en enklare situation senare. Vid återkommande, kraftig eller svår rädsla, kontakta veterinär först; efter medicinsk bedömning kan veterinären vid behov hänvisa till kvalificerad, belöningsbaserad beteendehjälp.') on conflict (id) do nothing;
insert into public.training_steps(id, program_version_id, step_key, position, title, instruction) values ('63000000-0000-4000-8000-000000000007'::uuid, '62000000-0000-4000-8000-000000000011'::uuid, 'positive-settle-area', 1, 'Gör viloplatsen trygg när du är hemma', 'Låt hunden utforska sin valda viloplats medan du finns i närheten. Du kan sitta lugnt där utan att kräva kontakt. Låt hunden själv stanna eller gå därifrån.') on conflict (id) do nothing;
insert into public.training_steps(id, program_version_id, step_key, position, title, instruction) values ('63000000-0000-4000-8000-000000000008'::uuid, '62000000-0000-4000-8000-000000000011'::uuid, 'small-distance', 2, 'Prova lite avstånd', 'När hunden är avslappnad på platsen, flytta dig en liten bit medan du fortfarande är hemma och återvänd medan den är lugn. Öka utmaningen bara efter att hunden bekvämt klarat det föregående steget.') on conflict (id) do nothing;
insert into public.training_steps(id, program_version_id, step_key, position, title, instruction) values ('63000000-0000-4000-8000-000000000009'::uuid, '62000000-0000-4000-8000-000000000011'::uuid, 'brief-out-of-sight', 3, 'Gå ur sikte och backa vid oro', 'När hunden klarar avståndet lugnt kan du kort gå ur sikte och komma tillbaka innan den blir orolig. Om den visar oro, avbryt och gå tillbaka till senast bekväma nivå. Vid kvarstående eller kraftig oro, kontakta veterinär först; efter medicinsk bedömning kan veterinären vid behov hänvisa till kvalificerad, belöningsbaserad beteendehjälp.') on conflict (id) do nothing;
do $verify_steps$
begin
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000001'::uuid) <> 0 then raise exception 'training step count mismatch: before-homecoming'; end if;
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000002'::uuid) <> 0 then raise exception 'training step count mismatch: first-week'; end if;
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000003'::uuid) <> 0 then raise exception 'training step count mismatch: daily-log-routines'; end if;
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000004'::uuid) <> 0 then raise exception 'training step count mismatch: handling-guide'; end if;
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000005'::uuid) <> 0 then raise exception 'training step count mismatch: environment-checklist'; end if;
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000006'::uuid) <> 0 then raise exception 'training step count mismatch: being-alone-guide'; end if;
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000007'::uuid) <> 0 then raise exception 'training step count mismatch: weight-history-guide'; end if;
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000008'::uuid) <> 0 then raise exception 'training step count mismatch: health-records-guide'; end if;
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000009'::uuid) <> 3 then raise exception 'training step count mismatch: handling-program'; end if;
  if not exists (select 1 from public.training_steps where id='63000000-0000-4000-8000-000000000001'::uuid and program_version_id='62000000-0000-4000-8000-000000000009'::uuid and step_key='voluntary-approach' and position=1 and title='Låt hunden välja kontakt' and instruction='Sitt stilla och erbjud en avslappnad hand en bit ifrån hunden. Belöna om hunden själv närmar sig eller nosar. Försök inte locka den närmare om den väljer att gå undan.') then raise exception 'training step mismatch: handling-program/voluntary-approach'; end if;
  if not exists (select 1 from public.training_steps where id='63000000-0000-4000-8000-000000000002'::uuid and program_version_id='62000000-0000-4000-8000-000000000009'::uuid and step_key='brief-touch' and position=2 and title='Prova en kort beröring' and instruction='När hunden självmant söker kontakt och verkar bekväm, prova en lätt, kort beröring på en plats den accepterar. Belöna och pausa direkt. Om den blir stel, vänder bort sig eller går undan (tolka signalerna tillsammans och i sitt sammanhang), sluta och återgå senare till steg 1.') then raise exception 'training step mismatch: handling-program/brief-touch'; end if;
  if not exists (select 1 from public.training_steps where id='63000000-0000-4000-8000-000000000003'::uuid and program_version_id='62000000-0000-4000-8000-000000000009'::uuid and step_key='choose-repeat' and position=3 and title='Låt hunden välja om ni fortsätter' and instruction='Erbjud samma enkla beröring igen en annan gång och pausa mellan försöken. Fortsätt bara när hunden själv stannar kvar och verkar bekväm. Avsluta om den visar obehag; gör inte övningen till fasthållning.') then raise exception 'training step mismatch: handling-program/choose-repeat'; end if;
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000010'::uuid) <> 3 then raise exception 'training step count mismatch: environment-program'; end if;
  if not exists (select 1 from public.training_steps where id='63000000-0000-4000-8000-000000000004'::uuid and program_version_id='62000000-0000-4000-8000-000000000010'::uuid and step_key='quiet-observe' and position=1 and title='Börja med att titta' and instruction='Välj en lugn och bekant plats. Låt hunden observera en vardagssak på avstånd där den verkar bekväm. Belöna frivillig uppmärksamhet och låt den vila eller gå undan.') then raise exception 'training step mismatch: environment-program/quiet-observe'; end if;
  if not exists (select 1 from public.training_steps where id='63000000-0000-4000-8000-000000000005'::uuid and program_version_id='62000000-0000-4000-8000-000000000010'::uuid and step_key='voluntary-explore' and position=2 and title='Låt hunden närma sig själv' and instruction='När hunden är lugn kan den själv få nosa eller närma sig samma sak. Belöna lugn nyfikenhet. Om den tvekar, stanna på lättare avstånd i stället för att föra den fram.') then raise exception 'training step mismatch: environment-program/voluntary-explore'; end if;
  if not exists (select 1 from public.training_steps where id='63000000-0000-4000-8000-000000000006'::uuid and program_version_id='62000000-0000-4000-8000-000000000010'::uuid and step_key='pause-or-backoff' and position=3 and title='Pausa när hunden behöver det' and instruction='Om hunden sänker kroppen, vänder bort sig, slickar sig om munnen eller försöker gå undan, avsluta och öka avståndet. Tolka signalerna tillsammans och i sitt sammanhang; en enstaka signal är inte en diagnos. Prova en enklare situation senare. Vid återkommande, kraftig eller svår rädsla, kontakta veterinär först; efter medicinsk bedömning kan veterinären vid behov hänvisa till kvalificerad, belöningsbaserad beteendehjälp.') then raise exception 'training step mismatch: environment-program/pause-or-backoff'; end if;
  if (select count(*) from public.training_steps where program_version_id='62000000-0000-4000-8000-000000000011'::uuid) <> 3 then raise exception 'training step count mismatch: being-alone-program'; end if;
  if not exists (select 1 from public.training_steps where id='63000000-0000-4000-8000-000000000007'::uuid and program_version_id='62000000-0000-4000-8000-000000000011'::uuid and step_key='positive-settle-area' and position=1 and title='Gör viloplatsen trygg när du är hemma' and instruction='Låt hunden utforska sin valda viloplats medan du finns i närheten. Du kan sitta lugnt där utan att kräva kontakt. Låt hunden själv stanna eller gå därifrån.') then raise exception 'training step mismatch: being-alone-program/positive-settle-area'; end if;
  if not exists (select 1 from public.training_steps where id='63000000-0000-4000-8000-000000000008'::uuid and program_version_id='62000000-0000-4000-8000-000000000011'::uuid and step_key='small-distance' and position=2 and title='Prova lite avstånd' and instruction='När hunden är avslappnad på platsen, flytta dig en liten bit medan du fortfarande är hemma och återvänd medan den är lugn. Öka utmaningen bara efter att hunden bekvämt klarat det föregående steget.') then raise exception 'training step mismatch: being-alone-program/small-distance'; end if;
  if not exists (select 1 from public.training_steps where id='63000000-0000-4000-8000-000000000009'::uuid and program_version_id='62000000-0000-4000-8000-000000000011'::uuid and step_key='brief-out-of-sight' and position=3 and title='Gå ur sikte och backa vid oro' and instruction='När hunden klarar avståndet lugnt kan du kort gå ur sikte och komma tillbaka innan den blir orolig. Om den visar oro, avbryt och gå tillbaka till senast bekväma nivå. Vid kvarstående eller kraftig oro, kontakta veterinär först; efter medicinsk bedömning kan veterinären vid behov hänvisa till kvalificerad, belöningsbaserad beteendehjälp.') then raise exception 'training step mismatch: being-alone-program/brief-out-of-sight'; end if;
end
$verify_steps$;
commit;
