import { Ionicons } from '@expo/vector-icons';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { tokens } from '../../theme/tokens';
type Mode = 'Home' | 'Back' | 'Close' | 'Title';
export type AppBarActionState = 'default' | 'pressed' | 'loading' | 'disabled' | 'success' | 'error';
export function AppBar({ mode, title, onAction, actionLabel, actionState = 'default' }: { mode: Mode; title: string; onAction?: () => void; actionLabel?: string; actionState?: AppBarActionState }) {
  const label = mode === 'Back' ? 'Tillbaka' : mode === 'Close' ? 'Stäng' : actionLabel ?? 'Notiser';
  const action = (icon: React.ComponentProps<typeof Ionicons>['name'], actionAccessibilityLabel: string) => <Pressable accessibilityRole="button" accessibilityLabel={actionLabel ?? actionAccessibilityLabel} accessibilityState={{ disabled: actionState === 'disabled' || actionState === 'loading', busy: actionState === 'loading' }} disabled={actionState === 'disabled' || actionState === 'loading'} onPress={onAction} style={({ pressed }) => [styles.action, (pressed || actionState === 'pressed') && styles.pressed, actionState === 'success' && styles.success, actionState === 'error' && styles.error]}>{actionState === 'loading' ? <ActivityIndicator color={tokens.colors.primary} /> : <Ionicons name={icon} size={tokens.size.iconMd} color={actionState === 'error' ? tokens.colors.danger : tokens.colors.textPrimary} />}</Pressable>;
  return <View style={styles.bar} accessibilityRole="header" accessibilityLabel={title}><View style={styles.side}>{mode === 'Home' ? <Text style={styles.brand}>Tassla</Text> : mode === 'Back' ? action('chevron-back', 'Tillbaka') : mode === 'Close' ? action('close', 'Stäng') : null}</View>{mode !== 'Home' ? <Text accessibilityRole="header" style={styles.title}>{title}</Text> : null}<View style={[styles.side, styles.right]}>{mode === 'Home' && onAction ? action('notifications-outline', label) : null}</View></View>;
}
const styles = StyleSheet.create({ bar: { alignSelf: 'stretch', minHeight: tokens.size.navHeight, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: tokens.spacing.sm, backgroundColor: tokens.colors.background }, side: { flex: 1, minHeight: tokens.size.touchMin, justifyContent: 'center' }, right: { alignItems: 'flex-end' }, action: { minWidth: tokens.size.touchMin, minHeight: tokens.size.touchMin, alignItems: 'center', justifyContent: 'center' }, pressed: { backgroundColor: tokens.colors.selectedSurface }, success: { backgroundColor: tokens.colors.successSurface }, error: { backgroundColor: tokens.colors.dangerSurface }, brand: { ...tokens.typography.title, color: tokens.colors.textPrimary }, title: { ...tokens.typography.heading, color: tokens.colors.textPrimary, textAlign: 'center', flexShrink: 1 } });
