import type { ReactNode } from 'react';
import { Ionicons } from '@expo/vector-icons';
import { KeyboardAvoidingView, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { tokens } from '../../theme/tokens';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useReducedMotion } from './Motion';
import { Button } from './Button';
export function BottomSheet({ visible, title, children, onRequestClose, onPrimaryAction, primaryLabel = 'Klar' }: { visible: boolean; title: string; children: ReactNode; onRequestClose: () => void; onPrimaryAction?: () => void; primaryLabel?: string }) {
  const reduced = useReducedMotion();
  const insets = useSafeAreaInsets();
  return <Modal visible={visible} transparent animationType={reduced ? 'none' : 'slide'} onRequestClose={onRequestClose} accessibilityViewIsModal><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={styles.backdrop}><Pressable accessibilityRole="button" accessibilityLabel="Stäng" onPress={onRequestClose} style={styles.dismissArea} /><View accessibilityRole="summary" accessibilityLabel={title} style={[styles.sheet, { paddingBottom: Math.max(insets.bottom, tokens.spacing.lg) }]}><View style={styles.heading}><Text accessibilityRole="header" style={styles.title}>{title}</Text><Pressable accessibilityRole="button" accessibilityLabel="Stäng" onPress={onRequestClose} style={styles.close}><Ionicons name="close" size={tokens.size.iconMd} color={tokens.colors.textPrimary} /></Pressable></View><ScrollView keyboardShouldPersistTaps="handled" keyboardDismissMode="on-drag" style={styles.scroll} contentContainerStyle={styles.content}>{children}</ScrollView>{onPrimaryAction ? <Button label={primaryLabel} accessibilityLabel={primaryLabel} onPress={onPrimaryAction} /> : null}</View></KeyboardAvoidingView></Modal>;
}
const styles = StyleSheet.create({ backdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: tokens.colors.overlay }, dismissArea: { flex: 1 }, sheet: { alignSelf: 'stretch', maxHeight: '90%', padding: tokens.spacing.lg, gap: tokens.spacing.md, borderTopLeftRadius: tokens.radius.lg, borderTopRightRadius: tokens.radius.lg, backgroundColor: tokens.colors.surface }, heading: { minHeight: tokens.size.touchMin, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: tokens.spacing.sm }, title: { ...tokens.typography.heading, color: tokens.colors.textPrimary, flex: 1, flexShrink: 1 }, close: { minWidth: tokens.size.touchMin, minHeight: tokens.size.touchMin, alignItems: 'center', justifyContent: 'center' }, scroll: { flexShrink: 1 }, content: { gap: tokens.spacing.md, paddingBottom: tokens.spacing.md } });
