import { StyleSheet, Text, View } from 'react-native';
import { tokens } from '../../theme/tokens';
import { Button } from './Button';
export type EmptyStateKind = 'empty' | 'loading' | 'error' | 'success' | 'disabled';
export function EmptyState({ title = 'Inget här än', description, actionLabel = 'Lägg till den första händelsen', onAction, state = 'empty' }: { title?: string; description?: string; actionLabel?: string; onAction?: () => void; state?: EmptyStateKind }) {
  const actionable = Boolean(onAction) && state !== 'loading' && state !== 'disabled';
  return <View accessibilityRole="summary" accessibilityLabel={title} accessibilityState={{ busy: state === 'loading', disabled: state === 'disabled' }} style={[styles.state, state === 'error' && styles.error, state === 'success' && styles.success, state === 'disabled' && styles.disabled]}><Text accessibilityRole="header" style={styles.title}>{title}</Text>{description ? <Text style={styles.description}>{description}</Text> : null}{actionable ? <Button label={actionLabel} accessibilityLabel={actionLabel} onPress={onAction!} variant={state === 'error' ? 'secondary' : 'primary'} state={state === 'error' ? 'error' : 'default'} /> : null}</View>;
}
const styles = StyleSheet.create({ state: { alignSelf: 'stretch', padding: tokens.spacing.lg, gap: tokens.spacing.md, borderRadius: tokens.radius.lg, backgroundColor: tokens.colors.surface, alignItems: 'stretch' }, error: { borderWidth: tokens.size.stroke, borderColor: tokens.colors.danger, backgroundColor: tokens.colors.dangerSurface }, success: { borderWidth: tokens.size.stroke, borderColor: tokens.colors.success, backgroundColor: tokens.colors.successSurface }, disabled: { opacity: tokens.opacity.disabled }, title: { ...tokens.typography.heading, color: tokens.colors.textPrimary, textAlign: 'center', flexShrink: 1 }, description: { ...tokens.typography.body, color: tokens.colors.textSecondary, textAlign: 'center' } });
