import { StyleSheet, Text, TextInput, View } from 'react-native';
import { tokens } from '../../theme/tokens';
type FieldKind = 'text' | 'date' | 'time' | 'multiline';
type FieldState = 'default' | 'focus' | 'filled' | 'error' | 'disabled';
export function Field({ label, value, onChangeText, kind = 'text', help, error, placeholder, state = 'default' }: { label: string; value: string; onChangeText: (value: string) => void; kind?: FieldKind; help?: string; error?: string; placeholder?: string; state?: FieldState }) {
  const multiline = kind === 'multiline';
  const keyboardType = kind === 'date' ? 'numbers-and-punctuation' : kind === 'time' ? 'numbers-and-punctuation' : 'default';
  const hint = kind === 'date' ? 'Skriv datum, till exempel 2026-10-07' : kind === 'time' ? 'Skriv tid, till exempel 12:05' : undefined;
  const disabled = state === 'disabled';
  return <View style={styles.field}><Text accessibilityRole="text" style={styles.label}>{label}</Text><TextInput accessibilityRole="text" accessibilityLabel={label} accessibilityHint={error ?? hint ?? help} editable={!disabled} value={value} onChangeText={onChangeText} placeholder={placeholder} keyboardType={keyboardType} multiline={multiline} textAlignVertical={multiline ? 'top' : 'center'} style={[styles.input, multiline && styles.multiline, (error || state === 'error') && styles.invalid, state === 'focus' && styles.focus, disabled && styles.disabled]} />{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : help ? <Text style={styles.help}>{help}</Text> : null}</View>;
}
const styles = StyleSheet.create({ field: { alignSelf: 'stretch', gap: tokens.spacing.xs }, label: { ...tokens.typography.label, color: tokens.colors.textPrimary }, input: { minHeight: tokens.size.buttonHeight, paddingHorizontal: tokens.spacing.md, borderWidth: tokens.size.stroke, borderColor: tokens.colors.borderStrong, borderRadius: tokens.radius.sm, backgroundColor: tokens.colors.surface, color: tokens.colors.textPrimary, ...tokens.typography.body }, multiline: { minHeight: tokens.size.buttonHeight * 2, paddingVertical: tokens.spacing.md }, invalid: { borderColor: tokens.colors.borderStrong }, focus: { borderColor: tokens.colors.primary }, disabled: { backgroundColor: tokens.colors.selectedSurface, opacity: 0.6 }, help: { ...tokens.typography.caption, color: tokens.colors.textSecondary }, error: { ...tokens.typography.caption, color: tokens.colors.danger } });
